/* COMPILE: -Wall -lm
 */

/* generates an integer square root table */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
	int n;
	int i;
	
	if(argc < 2){
		fprintf(stderr,"usage: genisqrt <range>\n");
		return 0;
	}
	
	n = strtol(argv[1], NULL, 0);
	
	printf("/* warning: do not edit this file.\n");
	printf(" * it has been automatically generated by genisqrt */\n\n");
	
	printf("#ifndef ISQRT_H\n");
	printf("#define ISQRT_H\n\n");
	
	printf("#define ISQRT_LEN %d\n", n);
	
	printf("static const int isqrt[%d] = {0", n);
	
	for(i=1;i<n;i++) printf(",%d",(int)sqrt((float)i));
	
	printf("};\n");
	printf("#endif /* ISQRT_H */\n");
	
	return 0;
}
